const techSkills = [
  "React.js",
  "Next.js",
  "TypeScript",
  "PostgreSQL",
  "Supabase",
  "Firebase",
  "Tailwind CSS",
  "Express.js",
  "MongoDB",
  "Git",
  "Bootstrap",
  "jQuery",
  "AWS",
  "Azure",
  "GCP (Google Cloud Platform)",
  "Docker",
  "Command line tools",
  "Windows",
  "Linux",
  "Python",
  "JavaScript",
  "Java",
  "C#",
  "PHP",
  "Bash scripting",
  "SQL",
  "MySQL",
  "MariaDB",
  "Oracle SQL",
  "MSSQL",
  "NoSQL",
  "HTML5",
  "CSS3",
  "Cypress",
  "Postman",
  "Axios",
  "nmap",
  "Metasploit",
  "bettercap",
  "gobuster",
  "ffuf",
  "airmon-ng",
  "Wireshark",
  "Machine Learning",
  "Xamarin Forms",
  "PL-SQL",
];

export default techSkills;
