-- Insert Categories
INSERT INTO categories (name, description) VALUES
('Frontend', 'Client-side development'),
('Backend', 'Server-side development'),
('Database', 'Data storage and management'),
('Cloud', 'Cloud computing platforms'),
('DevOps', 'Development and operations'),
('Tools', 'Development tools and utilities'),
('Programming Languages', 'Core programming languages'),
('Operating Systems', 'OS knowledge'),
('Security', 'Cybersecurity tools and practices'),
('Testing', 'Quality assurance and testing'),
('Mobile', 'Mobile application development'),
('AI/ML', 'Artificial Intelligence and Machine Learning')
ON CONFLICT (name) DO NOTHING;

-- Insert Skills
INSERT INTO skills (name, started_at) VALUES
('React.js', NOW() - INTERVAL '3 years'),
('Next.js', NOW() - INTERVAL '3 years'),
('TypeScript', NOW() - INTERVAL '2 years'),
('PostgreSQL', NOW() - INTERVAL '2 years'),
('Supabase', NOW() - INTERVAL '2 years'),
('Firebase', NOW() - INTERVAL '2 years'),
('Tailwind CSS', NOW() - INTERVAL '3 years'),
('Express.js', NOW() - INTERVAL '2 years'),
('MongoDB', NOW() - INTERVAL '1 years'),
('Git', NOW() - INTERVAL '5 years'),
('Bootstrap', NOW() - INTERVAL '1 years'),
('jQuery', NOW() - INTERVAL '1 years'),
('AWS', NOW() - INTERVAL '1 years'),
('Azure', NOW() - INTERVAL '1 years'),
('GCP (Google Cloud Platform)', NOW() - INTERVAL '2 years'),
('Docker', NOW() - INTERVAL '2 years'),
('Command line tools', NOW() - INTERVAL '5 years'),
('Windows', NOW() - INTERVAL '5 years'),
('Linux', NOW() - INTERVAL '3 years'),
('Python', NOW() - INTERVAL '3 years'),
('JavaScript', NOW() - INTERVAL '3 years'),
('Java', NOW() - INTERVAL '2 years'),
('C#', NOW() - INTERVAL '1 years'),
('PHP', NOW() - INTERVAL '1 years'),
('Bash scripting', NOW() - INTERVAL '1 years'),
('SQL', NOW() - INTERVAL '3 years'),
('MySQL', NOW() - INTERVAL '3 years'),
('MariaDB', NOW() - INTERVAL '1 years'),
('Oracle SQL', NOW() - INTERVAL '1 years'),
('MSSQL', NOW() - INTERVAL '1 years'),
('NoSQL', NOW() - INTERVAL '2 years'),
('HTML5', NOW() - INTERVAL '5 years'),
('CSS3', NOW() - INTERVAL '5 years'),
('Cypress', NOW() - INTERVAL '1 years'),
('Postman', NOW() - INTERVAL '2 years'),
('Axios', NOW() - INTERVAL '2 years'),
('nmap', NOW() - INTERVAL '1 years'),
('Metasploit', NOW() - INTERVAL '1 years'),
('bettercap', NOW() - INTERVAL '1 years'),
('gobuster', NOW() - INTERVAL '1 years'),
('ffuf', NOW() - INTERVAL '1 years'),
('airmon-ng', NOW() - INTERVAL '1 years'),
('Wireshark', NOW() - INTERVAL '1 years'),
('Machine Learning', NOW() - INTERVAL '1 years'),
('AI', NOW() - INTERVAL '1 years'),
('Xamarin Forms', NOW() - INTERVAL '1 years'),
('PL-SQL', NOW() - INTERVAL '1 years')
ON CONFLICT (name) DO UPDATE 
SET started_at = EXCLUDED.started_at; 

-- Map Skills to Categories
WITH map (skill_name, category_name) AS (
    VALUES
    ('React.js', 'Frontend'),
    ('Next.js', 'Frontend'),
    ('TypeScript', 'Programming Languages'),
    ('PostgreSQL', 'Database'),
    ('Supabase', 'Backend'),
    ('Firebase', 'Backend'),
    ('Tailwind CSS', 'Frontend'),
    ('Express.js', 'Backend'),
    ('MongoDB', 'Database'),
    ('Git', 'DevOps'),
    ('Bootstrap', 'Frontend'),
    ('jQuery', 'Frontend'),
    ('AWS', 'Cloud'),
    ('Azure', 'Cloud'),
    ('GCP (Google Cloud Platform)', 'Cloud'),
    ('Docker', 'DevOps'),
    ('Command line tools', 'Tools'),
    ('Windows', 'Operating Systems'),
    ('Linux', 'Operating Systems'),
    ('Python', 'Programming Languages'),
    ('JavaScript', 'Programming Languages'),
    ('Java', 'Programming Languages'),
    ('C#', 'Programming Languages'),
    ('PHP', 'Programming Languages'),
    ('Bash scripting', 'Programming Languages'),
    ('SQL', 'Programming Languages'),
    ('MySQL', 'Database'),
    ('MariaDB', 'Database'),
    ('Oracle SQL', 'Database'),
    ('MSSQL', 'Database'),
    ('NoSQL', 'Database'),
    ('HTML5', 'Frontend'),
    ('CSS3', 'Frontend'),
    ('Cypress', 'Testing'),
    ('Postman', 'Tools'),
    ('Axios', 'Tools'), 
    ('nmap', 'Security'),
    ('Metasploit', 'Security'),
    ('bettercap', 'Security'),
    ('gobuster', 'Security'),
    ('ffuf', 'Security'),
    ('airmon-ng', 'Security'),
    ('Wireshark', 'Security'),
    ('Machine Learning', 'AI/ML'),
    ('Xamarin Forms', 'Mobile'),
    ('PL-SQL', 'Database')
)
INSERT INTO skill_categories (skill_id, category_id)
SELECT s.id, c.id
FROM map m
JOIN skills s ON s.name = m.skill_name
JOIN categories c ON c.name = m.category_name
ON CONFLICT (skill_id, category_id) DO NOTHING;
